import { Project } from "@/components/ProjectCard";

export const projects: Project[] = [
  {
    id: 1,
    name: "Bakı Biznes Universiteti",
    name_en: "Baku Business University",
    subtitle: "Universitet Portalı",
    subtitle_en: "University Portal",
    description:
      "Təhsil müəssisəsi üçün müasir, yüksək performanslı rəsmi veb-sayt.",
    description_en:
      "Modern, high-performance official website for an educational institution.",
    technicalDetails: [
      "Next.js 16 və React 19 ilə performans optimallaşdırılması.",
      "next-intl vasitəsilə tam beynəlxalqlaşdırma (az/en) dəstəyi.",
      "Framer Motion ilə zəngin UI/UX animasiyaları.",
      "Oracle Cloud və Next.js Image vasitəsilə optimallaşdırılmış media delivery.",
    ],
    technicalDetails_en: [
      "Performance optimization with Next.js 16 and React 19.",
      "Full internationalization (az/en) support via next-intl.",
      "Rich UI/UX animations with Framer Motion.",
      "Optimized media delivery via Oracle Cloud and Next.js Image.",
    ],
    url: "https://bbu-next.vercel.app",
    tags: ["NEXT", "TS", "i18n"],
    image: "/images/projects/bbu.webp",
  },
  {
    id: 2,
    name: "BakuDivers",
    name_en: "BakuDivers",
    subtitle: "Dalış Mərkəzi",
    subtitle_en: "Diving Center",
    description:
      "Dalış mərkəzi üçün müasir və sürətli veb tətbiqin hazırlanması.",
    description_en:
      "Development of a modern and fast web application for a diving center.",
    technicalDetails: [
      "İstifadəçi dostu interfeys və asan naviqasiya.",
      "Xidmətlər və məhsullar üçün geniş kataloq sistemi.",
      "Backend üçün C# və SQL verilənlər bazası inteqrasiyası.",
      "Sürətli yüklənmə üçün React optimallaşdırmaları.",
    ],
    technicalDetails_en: [
      "User-friendly interface and easy navigation.",
      "Comprehensive catalog system for services and products.",
      "C# and SQL database integration for the backend.",
      "React optimizations for fast loading speeds.",
    ],
    url: "https://bakudivers.az",
    tags: ["React", "C#", "SQL"],
    image: "/images/projects/baku-divers.webp",
  },
  {
    id: 3,
    name: "Aznews",
    name_en: "Aznews",
    subtitle: "Xəbər Portalı",
    subtitle_en: "News Portal",
    description: "PHP Laravel platforması üzərində qurulmuş xəbər portalı.",
    description_en: "News portal built on the PHP Laravel platform.",
    technicalDetails: [
      "Laravel çərçivəsi ilə güclü inzibatçı paneli.",
      "Dinamik xəbər kateqoriyaları və teqlər sistemi.",
      "Yüksək trafik üçün verilənlər bazası optimallaşdırması.",
      "SEO dostu URL strukturu və meta-teqlər.",
    ],
    technicalDetails_en: [
      "Powerful admin panel built with Laravel framework.",
      "Dynamic news categories and tagging system.",
      "Database optimizations for high traffic handling.",
      "SEO-friendly URL structure and meta tags.",
    ],
    url: "https://aznews.rf.gd",
    tags: ["PHP", "LARAVEL", "MYSQL"],
    image: "/images/projects/aznews.webp",
  },
  {
    id: 4,
    name: "Bakı Biznes Universiteti Fayl Sistemi",
    name_en: "Baku Business University File System",
    subtitle: "Bulut Saxlanc Sistemi",
    subtitle_en: "Cloud Storage System",
    description: "Tələbələr və müəllimlər üçün daxili fayl idarəetmə sistemi.",
    description_en:
      "Internal file management system for students and teachers.",
    technicalDetails: [
      "Faylların təhlükəsiz yüklənməsi və idarə edilməsi.",
      "Tələbə və müəllimlər üçün xüsusi giriş hüquqları.",
      "Next.js App Router mühitində sürətli işləmə qabiliyyəti.",
      "Daxili axtarış və filtrasiya imkanları.",
    ],
    technicalDetails_en: [
      "Secure file upload and management system.",
      "Special access rights for students and teachers.",
      "Fast performance within Next.js App Router environment.",
      "Internal search and filtering capabilities.",
    ],
    url: "https://bbu-referat.vercel.app/",
    tags: ["Web", "NEXT", "FS"],
    image: "/images/projects/bbu-fs.webp",
  },
  {
    id: 5,
    name: "OBA Market Smart Reserve",
    name_en: "OBA Market Smart Reserve",
    subtitle: "Ağıllı Növbə Sistemi",
    subtitle_en: "Smart Queue System",
    description: "Marketlər üçün ağıllı rezervasiya və növbə sistemi MVP-si.",
    description_en: "Smart reservation and queue system MVP for markets.",
    technicalDetails: [
      "QR kod əsaslı sürətli rezervasiya mexanizmi.",
      "Real-vaxt növbə statusu izləmə interfeysi.",
      "Dashboard vasitəsilə mərkəzi market idarəetməsi.",
      "Yüngül və sürətli Next.js mühiti.",
    ],
    technicalDetails_en: [
      "QR code based fast reservation mechanism.",
      "Real-time queue status tracking interface.",
      "Centralized market management via dashboard.",
      "Lightweight and fast Next.js environment.",
    ],
    url: "https://smart-reserve-mvp.vercel.app/",
    tags: ["NEXT", "QR", "WEB"],
    image: "/images/projects/smart-reserve.webp",
  },
  {
    id: 6,
    name: "TripMind",
    name_en: "TripMind",
    subtitle: "AI Səyahət Planlama Platforması",
    subtitle_en: "AI Travel Planning Platform",
    description:
      "İstifadəçi büdcəsi və maraqlarına əsasən fərdiləşdirilmiş səyahət planı, ölkə tövsiyəsi və xərclər analizi təqdim edən AI əsaslı veb tətbiq.",
    description_en:
      "AI-powered web application that provides personalized travel plans, country recommendations, and budget analysis based on user preferences.",
    technicalDetails: [
      "Next.js 16 və React 19 ilə App Router əsaslı müasir arxitektura.",
      "Gemini və Groq API inteqrasiyası ilə AI tövsiyə və analiz sistemi.",
      "Kontekst əsaslı profil sistemi (büdcə, dillər, maraqlar, qida seçimləri).",
      "Unsplash API vasitəsilə dinamik məkan şəkilləri.",
      "Tailwind CSS 4 və TypeScript ilə tip təhlükəsiz və responsiv UI.",
    ],
    technicalDetails_en: [
      "Modern App Router architecture with Next.js 16 and React 19.",
      "AI recommendation and analysis system powered by Gemini and Groq APIs.",
      "Context-based profile system (budget, languages, interests, food preferences).",
      "Dynamic destination images via Unsplash API.",
      "Type-safe and responsive UI with Tailwind CSS 4 and TypeScript.",
    ],
    url: "https://tripmind-seven.vercel.app/",
    tags: ["NEXT", "AI", "TS", "TAILWIND"],
    image: "/images/projects/trip-mind.webp",
  },
  {
    id: 7,
    name: "RoadmapAI",
    name_en: "RoadmapAI",
    subtitle: "AI Əsaslı Yol Xəritəsi Platforması",
    subtitle_en: "AI-Powered Roadmap Platform",
    description:
      "İstifadəçilərin məqsədlərinə və maraqlarına əsasən fərdiləşdirilmiş inkişaf yol xəritələri təqdim edən AI əsaslı veb tətbiq.",
    description_en:
      "AI-powered web application that provides personalized development roadmaps based on user goals and interests.",
    technicalDetails: [
      "Next.js 16 və React 19 ilə App Router əsaslı interaktiv sorğu və nəticə səhifələri.",
      "AI əsaslı karyera testi: istifadəçi cavablarına görə ixtisas tövsiyəsi, confidence score və izahlı analiz.",
      "Addım-addım öyrənmə roadmap sistemi (təsvir, resurslar və praktik layihə tövsiyələri ilə).",
      "PDF export funksiyası ilə fərdiləşdirilmiş yol xəritəsinin endirilməsi.",
      "İkidilli interfeys (AZ/EN) və Light/Dark tema dəstəyi, Tailwind CSS 4 və TypeScript ilə responsiv UI.",
    ],
    technicalDetails_en: [
      "Interactive questionnaire and results pages built with Next.js 16 and React 19 using the App Router.",
      "AI-powered career assessment providing speciality recommendation, confidence score, and explanatory analysis.",
      "Step-by-step learning roadmap system with descriptions, curated resources, and practical project suggestions.",
      "PDF export functionality for downloading a personalized roadmap.",
      "Bilingual interface (AZ/EN) and Light/Dark theme support with a responsive, type-safe UI built using Tailwind CSS 4 and TypeScript.",
    ],
    url: "https://roadmap-one-neon.vercel.app/",
    tags: ["NEXT", "GEMINI", "AI"],
    image: "/images/projects/roadmap.webp",
  },
  {
    id: 8,
    name: "SolarSave",
    name_en: "SolarSave",
    subtitle: "Günəş Enerjisi ROI Kalkulyatoru",
    subtitle_en: "Solar ROI Calculator",
    description:
      "Azərbaycanda ev sahiblərinə günəş enerjisinə keçiddən əldə edə biləcəkləri qənaəti hesablamağa kömək edən tətbiq. Regional günəş saatları və elektrik tarifləri əsasında sistemin ölçüsünü, quraşdırma xərclərini və investisiyanın geri qayıtma müddətini hesablayır.",
    description_en:
      "A web application helping homeowners in Azerbaijan estimate their potential savings from switching to solar energy. Calculates system size, installation costs, and payback periods based on regional sun exposure and local electricity tariffs.",
    technicalDetails: [
      "Next.js 16, React 19 və Tailwind CSS 4 ilə hazırlanmış interaktiv və mobil cihazlara uyğun (mobile-first) UI.",
      "React Three Fiber və Three.js istifadə edilərək yaradılmış 3D arxa fon vizual effektləri.",
      "Azərbaycanın 14+ regionu üçün spesifik günəş saatı datası və ikipilləli elektrik tarifi (0–300 kWh və 300+ kWh) inteqrasiyası.",
      "Məişət texnikaları əsasında aylıq enerji istehlakını (kWh) hesablamaq üçün ağıllı interaktiv kalkulyator.",
      "Xüsusi React hook-ları (useWizard) ilə idarə olunan 3 addımlıq hesablama prosesi və İkidilli (AZ/EN) dəstək.",
    ],
    technicalDetails_en: [
      "Interactive, mobile-first UI built with Next.js 16, React 19, and Tailwind CSS 4.",
      "Immersive 3D background visual effects powered by React Three Fiber and Three.js.",
      "Region-specific sun hour data for 14+ regions in Azerbaijan and integration of the 2-tier electricity pricing system (0–300 kWh and 300+ kWh).",
      "Smart appliance-based interactive calculator to estimate monthly energy consumption (kWh).",
      "3-step calculation wizard managed by custom React hooks (useWizard) with bilingual (AZ/EN) interface support.",
    ],
    url: "https://roadmap-one-neon.vercel.app/",
    tags: ["NEXT", "REACT 19", "THREE.JS", "TAILWIND 4", "CALCULATOR"],
    image: "/images/projects/solar-save.webp",
  },
  {
    id: 9,
    name: "Soteria",
    name_en: "Soteria",
    subtitle: "Ətraf Mühit Monitorinqi və Proqnozlaşdırma Platforması",
    subtitle_en: "Environmental Monitoring & Forecasting Platform",
    description:
      "Xəzər regionu üçün peşəkar ətraf mühit monitorinqi platforması. NASA peyk görüntüləri, dərin meteoroloji datalar və Google Gemini AI analitikasını vahid ekosistemdə birləşdirir.",
    description_en:
      "Professional environmental monitoring platform for the Caspian region. Integrates NASA satellite imagery, deep meteorological data, and Google Gemini AI analytics into a single ecosystem.",
    technicalDetails: [
      "Next.js 15+ (App Router) və Tailwind CSS v4 ilə hazırlanmış, Leaflet.js əsaslı interaktiv çoxlaylı xəritə sistemi.",
      "NASA GIBS və EONET inteqrasiyası ilə canlı peyk analizi, tarixi arxiv naviqatoru və təbii hadisələrin izlənməsi.",
      "Open-Meteo API vasitəsilə hava keyfiyyəti (AQI, PM2.5, tozcuq), dəniz səviyyəsi və bərpa olunan enerji potensialının anlıq monitorinqi.",
      "Gemini 1.5 Pro vasitəsilə istifadəçi tərəfindən başladılan və lokal keşlənən AI əsaslı ekoloji və aqrar hesabatlar.",
      "Xətti və polinomial reqressiya modelləri ilə 7-30 günlük iqlim proyeksiyaları, həmçinin fermerlər üçün gəlirlilik (ROI) hesablamaları.",
    ],
    technicalDetails_en: [
      "Interactive multi-layer mapping system built with Next.js 15+ (App Router), Tailwind CSS v4, and Leaflet.js.",
      "Live satellite analysis, historical archive navigation, and natural event tracking integrated via NASA GIBS and EONET.",
      "Real-time monitoring of air quality (AQI, PM2.5, pollen), sea levels, and renewable energy potential via the Open-Meteo API.",
      "User-triggered, locally cached AI-driven ecological and agricultural reports powered by Gemini 1.5 Pro.",
      "7-30 day climate projections using linear and polynomial regression models, plus profitability/ROI calculators for farmers.",
    ],
    url: "https://soteriaz.vercel.app/",
    tags: ["NEXT", "GEMINI", "AI", "NASA API", "LEAFLET"],
    image: "/images/projects/soteria.webp",
  },
  {
    id: 10,
    name: "BBU Xarici Əlaqələr",
    name_en: "BBU International Relations",
    subtitle: "Universitet Portalı və Admin Panel",
    subtitle_en: "University Portal & Admin Panel",
    description:
      "Təhsil müəssisəsinin beynəlxalq əlaqələr şöbəsi üçün çoxdilli, interaktiv 3D elementlərə və tam funksional admin panelə malik müasir yüksək performanslı veb tətbiq.",
    description_en:
      "A modern, high-performance, multilingual web application for an educational institution's international relations department, featuring interactive 3D elements and a comprehensive admin panel.",
    technicalDetails: [
      "Next.js 16 (App Router), React 19 və Tailwind CSS 4 ilə hazırlanmış yüksək performanslı frontend arxitekturası.",
      "Three.js və React Three Fiber istifadə edərək 3D kampus modelləri və interaktiv qlobal tərəfdaşlıq qlobusu.",
      "next-intl vasitəsilə 3 dildə (AZ, EN, RU) tam lokallaşdırma və Leaflet ilə interaktiv xəritə inteqrasiyası.",
      "Xəbərlər, mobillik proqramları, tərəfdaş universitetlər və istifadəçi rollarını idarə etmək üçün təhlükəsiz admin panel.",
      "Framer Motion və Lottie React ilə zəngin UI/UX animasiyaları, həmçinin xüsusi backend API ilə real vaxt məlumat mübadiləsi.",
    ],
    technicalDetails_en: [
      "High-performance frontend architecture built with Next.js 16 (App Router), React 19, and Tailwind CSS 4.",
      "Interactive 3D campus models and global partnership globe powered by Three.js and React Three Fiber.",
      "Full localization in 3 languages (AZ, EN, RU) via next-intl and dynamic map integration using Leaflet.",
      "Secure admin panel for managing news, mobility applications, partner universities, and user roles.",
      "Rich UI/UX animations using Framer Motion and Lottie React, alongside real-time data integration with a custom backend API.",
    ],
    url: "https://bbu-ir.vercel.app",
    tags: [".NET", "NEXT", "THREE.JS", "i18n", "TAILWIND 4"],
    image: "/images/projects/bbu-ir.webp",
  },
];
